
# minikube start
# kubectl delete pods --all 
# minikube image load microapi-oracle-crud:latest -- for local
# kubectl get pods



apiVersion: apps/v1
kind: Deployment
metadata:
  name: micropi-oracle-crud-deployment
spec:
  replicas: 30   # run 3 containers (pods)
  selector:
    matchLabels:
      app: micropi-oracle-crud
  template:
    metadata:
      labels:
        app: micropi-oracle-crud
    spec:
      containers:
      - name: micropi-worker-operations
        image: microapi-worker-operations:v1.0.0
        ports:
        - containerPort: 8080
