apiVersion: v1
kind: Service
metadata:
  name: micropi-oracle-crud-service
spec:
  type: NodePort          # <- use NodePort for local testing
  selector:
    app: micropi-oracle-crud
  ports:
    - protocol: TCP
      port: 8080          # external port to access
      targetPort: 8080    # container port
      nodePort: 30080     # static NodePort (optional)
